# Generated by Django 5.2.15 on 2026-06-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Capability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("lang", "Langage"),
                            ("compiler", "Compilateur"),
                            ("cli", "CLI"),
                            ("stdlib", "Stdlib"),
                            ("pkg", "Paquets"),
                            ("wasm", "WASM & Web"),
                            ("lsp", "LSP & IDE"),
                            ("debug", "Debug"),
                            ("async", "Async & UI"),
                            ("ci", "Qualité & CI"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "items",
                    models.JSONField(
                        default=list, help_text="Liste de points (strings)"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Capabilities",
                "ordering": ["sort_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="CodeExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("title", models.CharField(max_length=128)),
                ("source", models.TextField()),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("featured", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["sort_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.SlugField(max_length=64, unique=True)),
                ("version", models.CharField(default="0.1.0", max_length=32)),
                ("description", models.TextField(blank=True)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("blessed", models.BooleanField(db_index=True, default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-blessed", "name"],
            },
        ),
        migrations.CreateModel(
            name="PlaygroundRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_hash", models.CharField(db_index=True, max_length=64)),
                ("target", models.CharField(default="native", max_length=32)),
                ("ok", models.BooleanField(default=False)),
                ("exit_code", models.IntegerField(default=1)),
                ("output_preview", models.TextField(blank=True)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
