# Generated by Django 5.2.15 on 2026-06-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=64, unique=True)),
                ("title", models.CharField(blank=True, max_length=256)),
                ("body", models.TextField()),
                ("released_at", models.DateField(blank=True, null=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["-sort_order", "-released_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("value", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Site metric",
            },
        ),
        migrations.CreateModel(
            name="StdlibModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.SlugField(max_length=128, unique=True)),
                ("import_path", models.CharField(max_length=256)),
                ("summary", models.CharField(blank=True, max_length=512)),
                ("function_count", models.PositiveSmallIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Stdlib module",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="codeexample",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
