# Generated by Django 5.2.15 on 2026-06-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_release_sitemetric_stdlibmodule_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stdlibmodule",
            name="name",
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
