name = "pkg_metier_demo"
version = "0.2.0"
main = "src/main.afr"
output = "build/pkg_metier_demo"
description = "Demo metier packages wave1+wave2"

[dependencies]
httpx = "0.1.0"
geox = "0.1.0"
datax = "0.1.0"
webapi = "0.1.0"
deployx = "0.1.0"
storex = "0.1.0"
apiclient = "0.1.0"
places = "0.1.0"
moneyx = "0.1.0"
csvtable = "0.1.0"
