#!/usr/bin/env python3
"""Module definitions for complex stdlib (modules 11-200). Used by .write_gen_complex.py."""
from __future__ import annotations

# fmt: off

def graph_rest() -> dict[str, list]:
    return {
    'graphprim': [
        ('primMst', 'number', [('adj','list number'),('n','number')],
         '{int nn=static_cast<int>(n);if(nn<=0)return 0;std::vector<double> key(nn,1e18);std::vector<bool> in(nn,false);key[0]=0;double total=0;for(int k=0;k<nn;++k){int u=-1;double best=1e18;for(int i=0;i<nn;++i)if(!in[i]&&key[i]<best){best=key[i];u=i;}if(u<0)break;in[u]=true;total+=key[u];for(int v=0;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);if(idx<adj.size()&&adj[idx]>0&&!in[v])key[v]=std::min(key[v],adj[idx]);}}return total;}'),
        ('primParents', 'list number', [('adj','list number'),('n','number')],
         '{int nn=static_cast<int>(n);std::vector<double> par(nn,-1),key(nn,1e18);std::vector<bool> in(nn,false);key[0]=0;for(int k=0;k<nn;++k){int u=-1;double best=1e18;for(int i=0;i<nn;++i)if(!in[i]&&key[i]<best){best=key[i];u=i;}if(u<0)break;in[u]=true;for(int v=0;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);if(idx<adj.size()&&adj[idx]>0&&!in[v]&&adj[idx]<key[v]){key[v]=adj[idx];par[v]=static_cast<double>(u);}}}return par;}'),
        ('primOrder', 'list number', [('adj','list number'),('n','number')],
         '{int nn=static_cast<int>(n);std::vector<double> order,key(nn,1e18);std::vector<bool> in(nn,false);key[0]=0;for(int k=0;k<nn;++k){int u=-1;double best=1e18;for(int i=0;i<nn;++i)if(!in[i]&&key[i]<best){best=key[i];u=i;}if(u<0)break;in[u]=true;order.push_back(static_cast<double>(u));for(int v=0;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);if(idx<adj.size()&&adj[idx]>0&&!in[v])key[v]=std::min(key[v],adj[idx]);}}return order;}'),
        ('mstEdgeCount', 'number', [('adj','list number'),('n','number')],
         '{int nn=static_cast<int>(n);return static_cast<double>(std::max(0,nn-1));}'),
        ('lightestEdge', 'number', [('adj','list number'),('n','number')],
         '{double m=1e18;for(double w:adj)if(w>0)m=std::min(m,w);return m>=1e18?0:m;}'),
        ('heaviestMstEdge', 'number', [('adj','list number'),('n','number')],
         '{int nn=static_cast<int>(n);std::vector<double> key(nn,1e18);std::vector<bool> in(nn,false);key[0]=0;double heaviest=0;for(int k=0;k<nn;++k){int u=-1;double best=1e18;for(int i=0;i<nn;++i)if(!in[i]&&key[i]<best){best=key[i];u=i;}if(u<0)break;in[u]=true;heaviest=std::max(heaviest,key[u]);for(int v=0;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);if(idx<adj.size()&&adj[idx]>0&&!in[v])key[v]=std::min(key[v],adj[idx]);}}return heaviest;}'),
        ('isPrimConnected', 'bool', [('adj','list number'),('n','number')],
         '{int nn=static_cast<int>(n);std::vector<bool> in(nn,false);std::vector<double> key(nn,1e18);key[0]=0;int cnt=0;for(int k=0;k<nn;++k){int u=-1;double best=1e18;for(int i=0;i<nn;++i)if(!in[i]&&key[i]<best){best=key[i];u=i;}if(u<0)break;in[u]=true;++cnt;for(int v=0;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);if(idx<adj.size()&&adj[idx]>0&&!in[v])key[v]=std::min(key[v],adj[idx]);}}return cnt==nn;}'),
    ],
    'graphkruskal': [
        ('kruskalMst', 'number', [('adj','list number'),('n','number')],
         '{int nn=static_cast<int>(n);struct E{int u,v;double w;};std::vector<E> es;for(int u=0;u<nn;++u)for(int v=u+1;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);if(idx<adj.size()&&adj[idx]>0)es.push_back({u,v,adj[idx]});}for(std::size_t i=es.size();i>1;--i){std::size_t j=static_cast<std::size_t>(std::rand()%(static_cast<int>(i)));std::swap(es[i-1],es[j]);}std::sort(es.begin(),es.end(),[](auto&a,auto&b){return a.w<b.w;});std::vector<int> p(nn);for(int i=0;i<nn;++i)p[i]=i;auto find=[&](int x){while(p[x]!=x)x=p[x];return x;};double total=0;int cnt=0;for(auto&e:es){int ru=find(e.u),rv=find(e.v);if(ru!=rv){p[ru]=rv;total+=e.w;if(++cnt==nn-1)break;}}return total;}'),
        ('kruskalEdges', 'list number', [('adj','list number'),('n','number')],
         '{int nn=static_cast<int>(n);struct E{int u,v;double w;};std::vector<E> es;for(int u=0;u<nn;++u)for(int v=u+1;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);if(idx<adj.size()&&adj[idx]>0)es.push_back({u,v,adj[idx]});}std::sort(es.begin(),es.end(),[](auto&a,auto&b){return a.w<b.w;});std::vector<int> p(nn);for(int i=0;i<nn;++i)p[i]=i;auto find=[&](int x){while(p[x]!=x)x=p[x];return x;};std::vector<double> picked;int cnt=0;for(auto&e:es){int ru=find(e.u),rv=find(e.v);if(ru!=rv){p[ru]=rv;picked.push_back(static_cast<double>(e.u));picked.push_back(static_cast<double>(e.v));picked.push_back(e.w);if(++cnt==nn-1)break;}}return picked;}'),
        ('unionFindComponents', 'number', [('adj','list number'),('n','number')],
         '{int nn=static_cast<int>(n);std::vector<int> p(nn);for(int i=0;i<nn;++i)p[i]=i;for(int u=0;u<nn;++u)for(int v=u+1;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);if(idx<adj.size()&&adj[idx]>0){int ru=u,rv=v;while(p[ru]!=ru)ru=p[ru];while(p[rv]!=rv)rv=p[rv];if(ru!=rv)p[ru]=rv;}}std::map<int,int> roots;for(int i=0;i<nn;++i){int r=i;while(p[r]!=r)r=p[r];++roots[r];}return static_cast<double>(roots.size());}'),
        ('edgeListSize', 'number', [('adj','list number'),('n','number')],
         '{int nn=static_cast<int>(n),c=0;for(int u=0;u<nn;++u)for(int v=u+1;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);if(idx<adj.size()&&adj[idx]>0)++c;}return static_cast<double>(c);}'),
        ('kruskalForestWeight', 'number', [('adj','list number'),('n','number')],
         'return kruskalMst(adj,n);'),
        ('maxSpanningForest', 'number', [('adj','list number'),('n','number')],
         '{int nn=static_cast<int>(n);struct E{int u,v;double w;};std::vector<E> es;for(int u=0;u<nn;++u)for(int v=u+1;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);if(idx<adj.size()&&adj[idx]>0)es.push_back({u,v,adj[idx]});}std::sort(es.begin(),es.end(),[](auto&a,auto&b){return a.w>b.w;});std::vector<int> p(nn);for(int i=0;i<nn;++i)p[i]=i;auto find=[&](int x){while(p[x]!=x)x=p[x];return x;};double total=0;for(auto&e:es){int ru=find(e.u),rv=find(e.v);if(ru!=rv){p[ru]=rv;total+=e.w;}}return total;}'),
        ('compareKruskalPrim', 'number', [('adj','list number'),('n','number')],
         '{double k=kruskalMst(adj,n);int nn=static_cast<int>(n);std::vector<double> key(nn,1e18);std::vector<bool> in(nn,false);key[0]=0;double p=0;for(int t=0;t<nn;++t){int u=-1;double best=1e18;for(int i=0;i<nn;++i)if(!in[i]&&key[i]<best){best=key[i];u=i;}if(u<0)break;in[u]=true;p+=key[u];for(int v=0;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);if(idx<adj.size()&&adj[idx]>0&&!in[v])key[v]=std::min(key[v],adj[idx]);}}return std::abs(k-p);}'),
    ],
    'graphbipart': [
        ('isBipartite', 'bool', [('adj','list number'),('n','number')],
         '{int nn=static_cast<int>(n);std::vector<int> color(nn,-1);for(int s=0;s<nn;++s){if(color[s]!=-1)continue;color[s]=0;std::vector<int> q;q.push_back(s);for(std::size_t qi=0;qi<q.size();++qi){int u=q[qi];for(int v=0;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);if(idx<adj.size()&&adj[idx]>0){if(color[v]==-1){color[v]=1-color[u];q.push_back(v);}else if(color[v]==color[u])return false;}}}return true;}'),
        ('bipartiteColors', 'list number', [('adj','list number'),('n','number')],
         '{int nn=static_cast<int>(n);std::vector<double> color(nn,-1);for(int s=0;s<nn;++s){if(color[s]>=0)continue;color[s]=0;std::vector<int> q;q.push_back(s);for(std::size_t qi=0;qi<q.size();++qi){int u=q[qi];for(int v=0;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);if(idx<adj.size()&&adj[idx]>0&&color[v]<0){color[v]=1-color[u];q.push_back(v);}}}std::vector<double> r;for(double c:color)r.push_back(c);return r;}'),
        ('partitionSizes', 'list number', [('adj','list number'),('n','number')],
         '{auto c=bipartiteColors(adj,n);double a=0,b=0;for(double x:c)if(x==0)++a;else if(x==1)++b;return std::vector<double>{a,b};}'),
        ('crossEdgeCount', 'number', [('adj','list number'),('n','number')],
         '{auto c=bipartiteColors(adj,n);int nn=static_cast<int>(n),cnt=0;for(int u=0;u<nn;++u)for(int v=0;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);if(idx<adj.size()&&adj[idx]>0&&c[u]!=c[v])++cnt;}return static_cast<double>(cnt);}'),
        ('sameSideEdges', 'number', [('adj','list number'),('n','number')],
         '{auto c=bipartiteColors(adj,n);int nn=static_cast<int>(n),cnt=0;for(int u=0;u<nn;++u)for(int v=u+1;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);if(idx<adj.size()&&adj[idx]>0&&c[u]==c[v])++cnt;}return static_cast<double>(cnt);}'),
        ('bipartiteDensity', 'number', [('adj','list number'),('n','number')],
         '{auto p=partitionSizes(adj,n);return p[0]*p[1]==0?0:crossEdgeCount(adj,n)/(p[0]*p[1]);}'),
        ('hasOddCycle', 'bool', [('adj','list number'),('n','number')],
         'return !isBipartite(adj,n);'),
    ],
    'grapheuler': [
        ('vertexDegrees', 'list number', [('adj','list number'),('n','number')],
         '{int nn=static_cast<int>(n);std::vector<double> d(nn,0);for(int u=0;u<nn;++u)for(int v=0;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);if(idx<adj.size()&&adj[idx]>0)d[u]+=1;}return d;}'),
        ('hasEulerCircuit', 'bool', [('adj','list number'),('n','number')],
         '{auto d=vertexDegrees(adj,n);int odd=0;for(double x:d)if(static_cast<int>(x)%2==1)++odd;return odd==0;}'),
        ('hasEulerPath', 'bool', [('adj','list number'),('n','number')],
         '{auto d=vertexDegrees(adj,n);int odd=0;for(double x:d)if(static_cast<int>(x)%2==1)++odd;return odd==0||odd==2;}'),
        ('oddDegreeCount', 'number', [('adj','list number'),('n','number')],
         '{auto d=vertexDegrees(adj,n);int c=0;for(double x:d)if(static_cast<int>(x)%2==1)++c;return static_cast<double>(c);}'),
        ('totalDegree', 'number', [('adj','list number'),('n','number')],
         '{auto d=vertexDegrees(adj,n);double s=0;for(double x:d)s+=x;return s;}'),
        ('eulerTrailLen', 'number', [('adj','list number'),('n','number')],
         '{int e=0;for(double w:adj)if(w>0)++e;return static_cast<double>(e)+1;}'),
        ('isEulerian', 'bool', [('adj','list number'),('n','number')],
         'return hasEulerPath(adj,n);'),
    ],
    'graphham': [
        ('hamiltonianExists', 'bool', [('adj','list number'),('n','number')],
         '{int nn=static_cast<int>(n);if(nn<=0||nn>12)return false;std::vector<int> path;std::vector<bool> vis(nn,false);std::function<bool(int)> dfs=[&](int u)->bool{if(static_cast<int>(path.size())==nn)return true;vis[u]=true;path.push_back(u);for(int v=0;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);if(idx<adj.size()&&adj[idx]>0&&!vis[v]&&dfs(v))return true;}vis[u]=false;path.pop_back();return false;};return dfs(0);}'),
        ('permuteCheck', 'number', [('adj','list number'),('n','number')],
         '{int nn=static_cast<int>(n);if(nn<=0||nn>8)return 0;std::vector<int> p(nn);for(int i=0;i<nn;++i)p[i]=i;int cnt=0;do{bool ok=true;for(int i=0;i<nn-1;++i){std::size_t idx=static_cast<std::size_t>(p[i]*nn+p[i+1]);if(idx>=adj.size()||adj[idx]<=0){ok=false;break;}}if(ok)++cnt;}while(std::next_permutation(p.begin(),p.end()));return static_cast<double>(cnt);}'),
        ('longestPath', 'number', [('adj','list number'),('n','number')],
         '{int nn=static_cast<int>(n);std::vector<bool> vis(nn,false);std::function<double(int)> dfs=[&](int u)->double{vis[u]=true;double best=1;for(int v=0;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);if(idx<adj.size()&&adj[idx]>0&&!vis[v])best=std::max(best,1+dfs(v));}vis[u]=false;return best;};return dfs(0);}'),
        ('hamiltonianCycle', 'bool', [('adj','list number'),('n','number')],
         '{int nn=static_cast<int>(n);if(nn<=1)return true;std::vector<bool> vis(nn,false);std::function<bool(int,int)> dfs=[&](int u,int depth)->bool{if(depth==nn){std::size_t idx=static_cast<std::size_t>(u*nn);return idx<adj.size()&&adj[idx]>0;}vis[u]=true;for(int v=0;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);if(idx<adj.size()&&adj[idx]>0&&!vis[v]&&dfs(v,depth+1))return true;}vis[u]=false;return false;};return dfs(0,1);}'),
        ('pathCoverSize', 'number', [('adj','list number'),('n','number')],
         'return longestPath(adj,n);'),
        ('tspLowerBound', 'number', [('adj','list number'),('n','number')],
         '{int nn=static_cast<int>(n);double s=0;for(int u=0;u<nn;++u){double mn=1e18;for(int v=0;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);if(idx<adj.size()&&adj[idx]>0)mn=std::min(mn,adj[idx]);}if(mn<1e18)s+=mn;}return s;}'),
        ('nearestNeighbor', 'list number', [('adj','list number'),('n','number'),('start','number')],
         '{int nn=static_cast<int>(n),cur=static_cast<int>(start);std::vector<double> tour;std::vector<bool> vis(nn,false);if(cur<0||cur>=nn)return std::vector<double>{};for(int step=0;step<nn;++step){vis[cur]=true;tour.push_back(static_cast<double>(cur));int nxt=-1;double best=1e18;for(int v=0;v<nn;++v){std::size_t idx=static_cast<std::size_t>(cur*nn+v);if(idx<adj.size()&&adj[idx]>0&&!vis[v]&&adj[idx]<best){best=adj[idx];nxt=v;}}if(nxt<0)break;cur=nxt;}return tour;}'),
    ],
    'graphclique': [
        ('maxCliqueSize', 'number', [('adj','list number'),('n','number')],
         '{int nn=static_cast<int>(n);if(nn>14)return 0;std::vector<int> best;std::function<void(int,std::vector<int>&)> bt=[&](int start,std::vector<int>& cur){if(cur.size()>best.size())best=cur;for(int v=start;v<nn;++v){bool ok=true;for(int u:cur){std::size_t idx=static_cast<std::size_t>(u*nn+v);if(idx>=adj.size()||adj[idx]<=0){ok=false;break;}}if(!ok)continue;cur.push_back(v);bt(v+1,cur);cur.pop_back();}};std::vector<int> cur;bt(0,cur);return static_cast<double>(best.size());}'),
        ('cliqueNumber', 'number', [('adj','list number'),('n','number')],
         'return maxCliqueSize(adj,n);'),
        ('isClique', 'bool', [('adj','list number'),('n','number'),('nodes','list number')],
         '{for(std::size_t i=0;i<nodes.size();++i)for(std::size_t j=i+1;j<nodes.size();++j){int u=static_cast<int>(nodes[i]),v=static_cast<int>(nodes[j]);std::size_t idx=static_cast<std::size_t>(u*static_cast<int>(n)+v);if(idx>=adj.size()||adj[idx]<=0)return false;}return nodes.size()>0;}'),
        ('cliqueCover', 'number', [('adj','list number'),('n','number')],
         '{int nn=static_cast<int>(n);return static_cast<double>(nn)/std::max(1.0,maxCliqueSize(adj,n));}'),
        ('triangleCount', 'number', [('adj','list number'),('n','number')],
         '{int nn=static_cast<int>(n),cnt=0;for(int i=0;i<nn;++i)for(int j=i+1;j<nn;++j)for(int k=j+1;k<nn;++k){std::size_t ij=static_cast<std::size_t>(i*nn+j),ik=static_cast<std::size_t>(i*nn+k),jk=static_cast<std::size_t>(j*nn+k);if(ij<adj.size()&&ik<adj.size()&&jk<adj.size()&&adj[ij]>0&&adj[ik]>0&&adj[jk]>0)++cnt;}return static_cast<double>(cnt);}'),
        ('clusteringCoeff', 'list number', [('adj','list number'),('n','number')],
         '{int nn=static_cast<int>(n);std::vector<double> cc(nn,0);for(int u=0;u<nn;++u){std::vector<int> nbr;for(int v=0;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);if(idx<adj.size()&&adj[idx]>0)nbr.push_back(v);}int k=static_cast<int>(nbr.size());if(k<2)continue;int edges=0;for(int i=0;i<k;++i)for(int j=i+1;j<k;++j){std::size_t idx=static_cast<std::size_t>(nbr[i]*nn+nbr[j]);if(idx<adj.size()&&adj[idx]>0)++edges;}cc[u]=2.0*edges/(k*(k-1));}return cc;}'),
        ('density', 'number', [('adj','list number'),('n','number')],
         '{int nn=static_cast<int>(n);if(nn<=1)return 0;int e=0;for(double w:adj)if(w>0)++e;return static_cast<double>(e)/(nn*(nn-1));}'),
    ],
    'graphcolor': [
        ('greedyColor', 'list number', [('adj','list number'),('n','number')],
         '{int nn=static_cast<int>(n);std::vector<double> color(nn,-1);for(int u=0;u<nn;++u){std::vector<bool> used(nn,false);for(int v=0;v<nn;++v){std::size_t idx=static_cast<std::size_t>(v*nn+u);if(idx<adj.size()&&adj[idx]>0&&color[v]>=0)used[static_cast<std::size_t>(color[v])]=true;}int c=0;while(c<nn&&used[static_cast<std::size_t>(c)])++c;color[u]=static_cast<double>(c);}return color;}'),
        ('chromaticNumber', 'number', [('adj','list number'),('n','number')],
         '{auto c=greedyColor(adj,n);double mx=0;for(double x:c)mx=std::max(mx,x);return mx+1;}'),
        ('isValidColoring', 'bool', [('adj','list number'),('n','number'),('colors','list number')],
         '{int nn=static_cast<int>(n);if(static_cast<int>(colors.size())<nn)return false;for(int u=0;u<nn;++u)for(int v=u+1;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);if(idx<adj.size()&&adj[idx]>0&&colors[static_cast<std::size_t>(u)]==colors[static_cast<std::size_t>(v)])return false;}return true;}'),
        ('colorClasses', 'list number', [('adj','list number'),('n','number')],
         '{auto c=greedyColor(adj,n);double mx=chromaticNumber(adj,n);std::vector<double> sz(static_cast<std::size_t>(mx),0);for(double x:c)sz[static_cast<std::size_t>(x)]+=1;return sz;}'),
        ('conflictCount', 'number', [('adj','list number'),('n','number'),('colors','list number')],
         '{int nn=static_cast<int>(n),cnt=0;for(int u=0;u<nn;++u)for(int v=u+1;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);if(idx<adj.size()&&adj[idx]>0&&u<static_cast<int>(colors.size())&&v<static_cast<int>(colors.size())&&colors[static_cast<std::size_t>(u)]==colors[static_cast<std::size_t>(v)])++cnt;}return static_cast<double>(cnt);}'),
        ('welshPowell', 'list number', [('adj','list number'),('n','number')],
         '{int nn=static_cast<int>(n);std::vector<std::pair<int,int>> deg;for(int u=0;u<nn;++u){int d=0;for(int v=0;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);if(idx<adj.size()&&adj[idx]>0)++d;}deg.emplace_back(d,u);}std::sort(deg.begin(),deg.end(),[](auto&a,auto&b){return a.first>b.first;});std::vector<double> color(nn,-1);for(auto&p:deg){int u=p.second;std::vector<bool> used(nn,false);for(int v=0;v<nn;++v){std::size_t idx=static_cast<std::size_t>(v*nn+u);if(idx<adj.size()&&adj[idx]>0&&color[v]>=0)used[static_cast<std::size_t>(color[v])]=true;}int c=0;while(c<nn&&used[static_cast<std::size_t>(c)])++c;color[u]=static_cast<double>(c);}return color;}'),
        ('sameColorNeighbors', 'number', [('adj','list number'),('n','number'),('node','number')],
         '{auto c=greedyColor(adj,n);int u=static_cast<int>(node),nn=static_cast<int>(n),cnt=0;if(u<0||u>=nn)return 0;for(int v=0;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);if(idx<adj.size()&&adj[idx]>0&&c[static_cast<std::size_t>(v)]==c[static_cast<std::size_t>(u)])++cnt;}return static_cast<double>(cnt);}'),
    ],
    'graphflow': [
        ('maxFlow', 'number', [('adj','list number'),('n','number'),('source','number'),('sink','number')],
         '{int nn=static_cast<int>(n),s=static_cast<int>(source),t=static_cast<int>(sink);if(s<0||t<0||s>=nn||t>=nn)return 0;std::vector<double> flow(static_cast<std::size_t>(nn*nn),0);double total=0;auto bfs=[&]()->int{std::vector<int> prev(nn,-1);std::vector<bool> vis(nn,false);std::vector<int> q;q.push_back(s);vis[s]=true;for(std::size_t qi=0;qi<q.size();++qi){int u=q[qi];for(int v=0;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);double cap=idx<adj.size()?adj[idx]:0;std::size_t fi=static_cast<std::size_t>(u*nn+v);if(!vis[v]&&cap-flow[fi]>1e-9){vis[v]=true;prev[v]=u;q.push_back(v);}}}return prev[t];};while(true){std::vector<int> prev(nn,-1);std::vector<bool> vis(nn,false);std::vector<int> q;q.push_back(s);vis[s]=true;for(std::size_t qi=0;qi<q.size();++qi){int u=q[qi];for(int v=0;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);double cap=idx<adj.size()?adj[idx]:0;std::size_t fi=static_cast<std::size_t>(u*nn+v);if(!vis[v]&&cap-flow[fi]>1e-9){vis[v]=true;prev[v]=u;q.push_back(v);}}}if(!vis[t])break;double f=1e18;for(int v=t;v!=s;v=prev[v]){int u=prev[v];std::size_t fi=static_cast<std::size_t>(u*nn+v);f=std::min(f,(adj[fi]-flow[fi]));}for(int v=t;v!=s;v=prev[v]){int u=prev[v];std::size_t fi=static_cast<std::size_t>(u*nn+v),fb=static_cast<std::size_t>(v*nn+u);flow[fi]+=f;flow[fb]-=f;}total+=f;}return total;}'),
        ('minCutValue', 'number', [('adj','list number'),('n','number'),('source','number'),('sink','number')],
         'return maxFlow(adj,n,source,sink);'),
        ('flowMatrix', 'list number', [('adj','list number'),('n','number'),('source','number'),('sink','number')],
         '{int nn=static_cast<int>(n),s=static_cast<int>(source),t=static_cast<int>(sink);std::vector<double> flow(static_cast<std::size_t>(nn*nn),0);double total=0;while(true){std::vector<int> prev(nn,-1);std::vector<bool> vis(nn,false);std::vector<int> q;q.push_back(s);vis[s]=true;for(std::size_t qi=0;qi<q.size();++qi){int u=q[qi];for(int v=0;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);double cap=idx<adj.size()?adj[idx]:0;std::size_t fi=static_cast<std::size_t>(u*nn+v);if(!vis[v]&&cap-flow[fi]>1e-9){vis[v]=true;prev[v]=u;q.push_back(v);}}}if(!vis[t])break;double f=1e18;for(int v=t;v!=s;v=prev[v]){int u=prev[v];std::size_t fi=static_cast<std::size_t>(u*nn+v);f=std::min(f,adj[fi]-flow[fi]);}for(int v=t;v!=s;v=prev[v]){int u=prev[v];std::size_t fi=static_cast<std::size_t>(u*nn+v),fb=static_cast<std::size_t>(v*nn+u);flow[fi]+=f;flow[fb]-=f;}total+=f;}return flow;}'),
        ('bottleneckCapacity', 'number', [('adj','list number'),('n','number')],
         '{double m=1e18;for(double w:adj)if(w>0)m=std::min(m,w);return m>=1e18?0:m;}'),
        ('outFlowSum', 'number', [('adj','list number'),('n','number'),('node','number')],
         '{int u=static_cast<int>(node),nn=static_cast<int>(n);double s=0;for(int v=0;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);if(idx<adj.size()&&adj[idx]>0)s+=adj[idx];}return s;}'),
        ('inFlowSum', 'number', [('adj','list number'),('n','number'),('node','number')],
         '{int v=static_cast<int>(node),nn=static_cast<int>(n);double s=0;for(int u=0;u<nn;++u){std::size_t idx=static_cast<std::size_t>(u*nn+v);if(idx<adj.size()&&adj[idx]>0)s+=adj[idx];}return s;}'),
        ('isFlowConserved', 'bool', [('adj','list number'),('n','number'),('source','number'),('sink','number')],
         '{double f=maxFlow(adj,n,source,sink);return f>=0;}'),
    ],
    'graphmatch': [
        ('maxMatching', 'number', [('adj','list number'),('n','number')],
         '{int nn=static_cast<int>(n);std::vector<int> match(nn,-1);std::function<bool(int,std::vector<bool>&)> aug=[&](int u,std::vector<bool>& vis)->bool{for(int v=0;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);if(idx<adj.size()&&adj[idx]>0&&!vis[v]){vis[v]=true;int w=match[v];if(w<0||aug(w,vis)){match[v]=u;match[u]=v;return true;}}}return false;};int cnt=0;for(int u=0;u<nn;++u){if(match[u]<0){std::vector<bool> vis(nn,false);if(aug(u,vis))++cnt;}}return static_cast<double>(cnt);}'),
        ('matchingPairs', 'list number', [('adj','list number'),('n','number')],
         '{int nn=static_cast<int>(n);std::vector<int> match(nn,-1);std::function<bool(int,std::vector<bool>&)> aug=[&](int u,std::vector<bool>& vis)->bool{for(int v=0;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);if(idx<adj.size()&&adj[idx]>0&&!vis[v]){vis[v]=true;int w=match[v];if(w<0||aug(w,vis)){match[v]=u;match[u]=v;return true;}}}return false;};for(int u=0;u<nn;++u)if(match[u]<0){std::vector<bool> vis(nn,false);aug(u,vis);}std::vector<double> pairs;for(int v=0;v<nn;++v)if(match[v]>v){pairs.push_back(static_cast<double>(v));pairs.push_back(static_cast<double>(match[v]));}return pairs;}'),
        ('isPerfectMatching', 'bool', [('adj','list number'),('n','number')],
         '{double m=maxMatching(adj,n);return m*2==static_cast<double>(n);}'),
        ('unmatchedCount', 'number', [('adj','list number'),('n','number')],
         '{int nn=static_cast<int>(n);std::vector<int> match(nn,-1);std::function<bool(int,std::vector<bool>&)> aug=[&](int u,std::vector<bool>& vis)->bool{for(int v=0;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);if(idx<adj.size()&&adj[idx]>0&&!vis[v]){vis[v]=true;int w=match[v];if(w<0||aug(w,vis)){match[v]=u;match[u]=v;return true;}}}return false;};for(int u=0;u<nn;++u)if(match[u]<0){std::vector<bool> vis(nn,false);aug(u,vis);}int c=0;for(int i=0;i<nn;++i)if(match[i]<0)++c;return static_cast<double>(c);}'),
        ('matchingWeight', 'number', [('adj','list number'),('n','number')],
         '{auto p=matchingPairs(adj,n);double s=0;for(std::size_t i=0;i+1<p.size();i+=2){int u=static_cast<int>(p[i]),v=static_cast<int>(p[i+1]);std::size_t idx=static_cast<std::size_t>(u*static_cast<int>(n)+v);if(idx<adj.size())s+=adj[idx];}return s;}'),
        ('vertexCoverSize', 'number', [('adj','list number'),('n','number')],
         'return maxMatching(adj,n);'),
        ('isMatched', 'bool', [('adj','list number'),('n','number'),('node','number')],
         '{int nn=static_cast<int>(n);std::vector<int> match(nn,-1);std::function<bool(int,std::vector<bool>&)> aug=[&](int u,std::vector<bool>& vis)->bool{for(int v=0;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);if(idx<adj.size()&&adj[idx]>0&&!vis[v]){vis[v]=true;int w=match[v];if(w<0||aug(w,vis)){match[v]=u;match[u]=v;return true;}}}return false;};for(int u=0;u<nn;++u)if(match[u]<0){std::vector<bool> vis(nn,false);aug(u,vis);}int nd=static_cast<int>(node);return nd>=0&&nd<nn&&match[nd]>=0;}'),
    ],
    'graphcent': [
        ('degreeCentrality', 'list number', [('adj','list number'),('n','number')],
         '{int nn=static_cast<int>(n);std::vector<double> d(nn,0);for(int u=0;u<nn;++u)for(int v=0;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);if(idx<adj.size()&&adj[idx]>0)d[u]+=1;}if(nn<=1)return d;for(double&x:d)x/=(nn-1);return d;}'),
        ('closenessCentrality', 'list number', [('adj','list number'),('n','number')],
         '{int nn=static_cast<int>(n);std::vector<double> cc(nn,0);for(int s=0;s<nn;++s){std::vector<double> dist(nn,-1);std::vector<int> q;dist[s]=0;q.push_back(s);for(std::size_t qi=0;qi<q.size();++qi){int u=q[qi];for(int v=0;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);if(idx<adj.size()&&adj[idx]>0&&dist[v]<0){dist[v]=dist[u]+1;q.push_back(v);}}}double sum=0;int reach=0;for(int v=0;v<nn;++v)if(v!=s&&dist[v]>0){sum+=dist[v];++reach;}cc[s]=reach==0?0:static_cast<double>(reach)/sum;}return cc;}'),
        ('betweennessApprox', 'list number', [('adj','list number'),('n','number')],
         '{int nn=static_cast<int>(n);std::vector<double> bc(nn,0);for(int s=0;s<nn;++s){std::vector<double> dist(nn,-1);std::vector<int> q;dist[s]=0;q.push_back(s);for(std::size_t qi=0;qi<q.size();++qi){int u=q[qi];for(int v=0;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);if(idx<adj.size()&&adj[idx]>0&&dist[v]<0){dist[v]=dist[u]+1;q.push_back(v);if(u!=s&&v!=s)bc[u]+=1;}}}return bc;}'),
        ('eigenvectorCentrality', 'list number', [('adj','list number'),('n','number')],
         '{int nn=static_cast<int>(n);std::vector<double> x(nn,1.0/nn);for(int iter=0;iter<20;++iter){std::vector<double> nx(nn,0);for(int u=0;u<nn;++u)for(int v=0;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);if(idx<adj.size()&&adj[idx]>0)nx[v]+=x[u];}double norm=0;for(double v:nx)norm+=v*v;norm=std::sqrt(norm);if(norm<1e-12)break;for(int i=0;i<nn;++i)x[i]=nx[i]/norm;}return x;}'),
        ('pageRank', 'list number', [('adj','list number'),('n','number'),('damping','number')],
         '{int nn=static_cast<int>(n);double d=damping;std::vector<double> pr(nn,1.0/nn),outdeg(nn,0);for(int u=0;u<nn;++u)for(int v=0;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);if(idx<adj.size()&&adj[idx]>0)outdeg[u]+=1;}for(int iter=0;iter<25;++iter){std::vector<double> npr(nn,(1-d)/nn);for(int u=0;u<nn;++u)if(outdeg[u]>0)for(int v=0;v<nn;++v){std::size_t idx=static_cast<std::size_t>(u*nn+v);if(idx<adj.size()&&adj[idx]>0)npr[v]+=d*pr[u]/outdeg[u];}pr=npr;}return pr;}'),
        ('hubScore', 'list number', [('adj','list number'),('n','number')],
         'return eigenvectorCentrality(adj,n);'),
        ('mostCentral', 'number', [('adj','list number'),('n','number')],
         '{auto c=closenessCentrality(adj,n);if(c.empty())return 0;return static_cast<double>(std::max_element(c.begin(),c.end())-c.begin());}'),
    ],
    }
