"""UI strings FR/EN — site officiel AFRILANG."""

UI = {
    'fr': {
        'nav_language': 'Le langage',
        'nav_docs': 'Documentation',
        'nav_ecosystem': 'Écosystème',
        'nav_benchmarks': 'Benchmarks',
        'nav_showcase': 'Projets',
        'nav_packages': 'Paquets',
        'nav_playground': 'Playground',
        'nav_tutorial': 'Tutoriel',
        'nav_examples': 'Exemples',
        'nav_stdlib': 'Stdlib',
        'nav_libraries': 'Bibliothèques',
        'nav_download': 'Télécharger',
        'nav_community': 'Communauté',
        'nav_api': 'API',
        'nav_github': 'GitHub',
        'nav_more': 'Plus',
        'nav_start': 'Commencer',
        'nav_theme_light': 'Mode clair',
        'nav_theme_dark': 'Mode sombre',
        'nav_version_label': 'Langage · v',
        'skip_link': 'Aller au contenu principal',
        'footer_learn': 'Apprendre',
        'footer_reference': 'Référence',
        'footer_community': 'Communauté',
        'footer_versions': 'Versions',
        'footer_lang': 'Langage',
        'footer_compiler': 'Compilateur',
        'footer_tagline': 'Codez en phrases, déployez en natif.',
        'footer_desc': (
            'Langage orienté objet à syntaxe naturelle. Transpile vers C++17 '
            'et compile en binaire natif. Open source, licence MIT.'
        ),
        'cookie_text': 'Ce site utilise des cookies de session pour la langue et le playground.',
        'cookie_accept': 'Accepter',
        'cookie_decline': 'Refuser',
        'meta_default': (
            'AFRILANG — langage orienté objet à syntaxe naturelle, transpile vers C++17, '
            'bibliothèque standard riche, outils LSP et playground.'
        ),
        'home': {
            'title': 'AFRILANG — Codez en phrases, déployez en natif',
            'badge': 'Open source · MIT',
            'brand': 'AFRILANG',
            'hero_h1_a': 'Codez en',
            'hero_h1_b': 'langage naturel',
            'hero_h1_c': 'compilez en natif.',
            'hero_lead': (
                'Langage orienté objet à syntaxe lisible : transpile vers C++17, '
                'compile en binaire natif. Français et anglais.'
            ),
            'hero_compat': 'LSP · REPL · WASM · cross-compilation',
            'btn_start': 'Commencer',
            'btn_try': 'Playground',
            'btn_tutorial': 'Tutoriel interactif',
            'stat_examples': 'Exemples',
            'stat_stdlib': 'Modules stdlib',
            'stat_packages': 'Paquets certifiés',
            'stat_targets': 'Cibles (x64, ARM, WASM)',
            'why_label': 'Pourquoi AFRILANG',
            'why_title': 'Lisible comme une phrase, performant comme du C++',
            'why_desc': (
                "Syntaxe naturelle, erreurs explicites, toolchain moderne "
                'et écosystème open source.'
            ),
            'feat_natural_title': 'Syntaxe naturelle',
            'feat_natural': (
                '<code>if age is greater than 18 then</code> — mots-clés en français '
                '(<code>dire</code>, <code>si</code>, <code>fin</code>) ou en anglais.'
            ),
            'feat_perf_title': 'Performance native',
            'feat_perf': (
                'Transpilation C++17 puis <code>g++</code>. Binaires natifs, '
                'linux-x64, linux-arm64 et wasm32.'
            ),
            'feat_tools_title': 'Toolchain intégrée',
            'feat_tools': (
                'CLI, LSP, REPL, debug, extension VS Code/Cursor et playground web.'
            ),
            'example_label': 'Exemple rapide',
            'example_title': 'De la phrase au binaire en une commande',
            'example_desc': (
                'Installez le compilateur, écrivez un fichier <code>.afr</code>, exécutez-le. '
                'Le pipeline transpile vers C++ puis invoque <code>g++</code> automatiquement.'
            ),
            'packages_label': 'Écosystème',
            'packages_title': 'Paquets certifiés',
            'packages_all': 'Voir tout →',
            'packages_empty': 'Registre vide — lancez <code>python manage.py sync_packages</code>',
            'cta_title': 'Prêt à écrire votre premier programme ?',
            'cta_desc': 'Installez le compilateur ou suivez le guide de démarrage.',
            'cta_guide': 'Guide de démarrage',
            'cta_lang': 'Découvrir le langage',
            'cta_play': 'Playground',
            'cta_tutorial': 'Tutoriel interactif',
        },
        'tutorial_page': {
            'title': 'Tutoriel AFRILANG',
            'label': 'Apprendre',
            'h1': 'Tutoriel interactif',
            'lead': '7 leçons guidées — de Hello World à la POO et au pattern matching.',
            'sidebar': 'Parcours',
            'step_label': 'Étape',
            'objectives': 'Objectifs',
            'code_title': 'Code de la leçon',
            'copy': 'Copier',
            'try_playground': 'Essayer dans le playground',
            'challenge': 'Défi',
            'prev': 'Précédent',
            'next': 'Suivant',
            'overview': 'Vue d\'ensemble',
            'mark_done': 'Marquer comme terminé',
            'finish': 'Installer le compilateur',
            'read_doc': 'Lire la documentation →',
            'start': 'Commencer le tutoriel',
            'completed': 'terminées',
        },
        'language_page': {
            'title': 'Le langage AFRILANG',
            'meta': 'Présentation d\'AFRILANG : syntaxe naturelle bilingue, transpilation C++, POO, génériques, async.',
            'label': 'AFRILANG {version}',
            'h1': 'Un langage qui se lit, un compilateur qui livre',
            'lead': (
                'AFRILANG combine la lisibilité du langage naturel avec la rigueur d\'un compilateur moderne. '
                'Vous écrivez des programmes qui ressemblent à des phrases ; le compilateur les transforme '
                'en C++17 optimisé, puis en exécutables natifs.'
            ),
        },
        'download': {
            'title': 'Télécharger AFRILANG',
            'h1': 'Installer le compilateur',
            'lead': 'Binaire précompilé, script d\'installation ou compilation depuis les sources.',
            'binary_title': 'Binaire précompilé',
            'binary_lead': 'Téléchargez le compilateur compilé sur ce serveur (Linux x64).',
            'binary_download': 'Télécharger',
            'binary_none': 'Aucun binaire disponible sur ce serveur — compilez depuis les sources ou consultez GitHub Releases.',
            'binary_sha256': 'SHA256',
            'binary_size': 'Taille',
            'install_title': 'Installation rapide',
            'install_lead': 'Script bash — clone, compile et installe dans ~/.local/afrilang',
            'github_title': 'GitHub Releases',
            'github_lead': 'Versions officielles et artefacts CI sur GitHub.',
            'github_btn': 'Voir les releases',
            'requirements': 'Prérequis',
            'build': 'Compilation depuis les sources',
            'verify': 'Vérification',
            'ide': 'Extension IDE',
        },
        'community': {
            'title': 'Communauté AFRILANG',
            'h1': 'Rejoindre la communauté',
            'lead': 'Contribuer, signaler des bugs, publier des paquets et participer au projet open source.',
        },
        'api_page': {
            'title': 'API REST — Playground',
            'h1': 'API HTTP du playground',
            'lead': 'Endpoints JSON pour exécuter, formater et lister les paquets AFRILANG.',
            'run_desc': 'Exécute du source AFRILANG (compilation native).',
            'fmt_desc': 'Formate le source et renvoie le code formaté.',
            'pkg_desc': 'Liste tous les paquets du registre.',
        },
        'explore': {
            'title': 'Écosystème AFRILANG',
            'label': 'Écosystème complet',
            'h1': 'Tout ce qui compose AFRILANG',
            'lead': 'Langage, compilateur, stdlib, paquets, WASM, LSP, debug et CI.',
            'empty': 'Données non chargées — exécutez python manage.py seed_data',
            'btn_tools': 'Documentation outils',
            'btn_packages': 'Registre de paquets',
        },
        'packages_page': {
            'title': 'Paquets AFRILANG',
            'label': 'Gestionnaire de paquets',
            'h1': 'Registre officiel',
            'lead': 'Paquets certifiés (★) avec vérification SHA256.',
            'search': 'Rechercher un paquet…',
            'filter': 'Filtrer',
            'empty': 'Aucun paquet trouvé.',
            'usage_title': 'Utiliser un paquet',
        },
        'playground_page': {
            'title': 'Playground AFRILANG',
            'label': 'Essayer en ligne',
            'h1': 'Playground AFRILANG',
            'lead': 'Écrivez du code, exécutez-le, vérifiez-le ou formatez-le en direct.',
            'example': 'Exemple',
            'run': 'Run',
            'run_browser': 'Navigateur',
            'wasm': 'WASM navigateur',
            'format': 'Format',
            'check': 'Check',
            'share': 'Partager',
            'copy_output': 'Copier',
            'output': 'Sortie',
            'output_hint': 'Cliquez sur Run pour exécuter votre code.',
            'help': 'Consultez la syntaxe de base ou les premiers pas.',
            'shortcut_run': 'Ctrl+Entrée pour exécuter',
            'wasm_hint': 'Exécution instantanée dans le navigateur — sans charge serveur pour les programmes simples.',
            'embed_link': 'Intégrer (iframe)',
        },
        'playground_embed_page': {
            'title': 'Intégrer le playground',
            'label': 'Embed',
            'h1': 'Widget playground',
            'lead': 'Intégrez l\'éditeur AFRILANG dans votre blog, documentation ou site via une iframe.',
            'widget_title': 'AFRILANG Playground',
            'builder': 'Générateur d\'iframe',
            'example': 'Exemple',
            'height': 'Hauteur (px)',
            'show_examples': 'Afficher le sélecteur d\'exemples',
            'copy': 'Copier le code',
            'code_title': 'Code HTML',
            'preview': 'Aperçu',
            'open_widget': 'Ouvrir le widget',
            'params_title': 'Paramètres URL',
            'param_example': 'exemple préchargé',
            'param_examples': 'menu des exemples',
            'param_code': 'code source (URL-encodé)',
        },
        'examples_page': {
            'title': 'Exemples AFRILANG',
            'label': 'Galerie',
            'h1': 'Exemples officiels',
            'lead': 'Programmes du dépôt examples/ — ouvrez-les dans le playground en un clic.',
            'search': 'Rechercher un exemple…',
            'filter': 'Filtrer',
            'empty': 'Aucun exemple — lancez python manage.py sync_examples',
            'try_btn': 'Essayer',
        },
        'stdlib_page': {
            'title': 'Bibliothèque standard',
            'label': 'Stdlib',
            'h1': 'Navigateur stdlib',
            'lead': 'Parcourez les modules de la bibliothèque standard AFRILANG.',
            'search': 'Rechercher un module…',
            'filter': 'Filtrer',
            'empty': 'Aucun module — lancez python manage.py sync_stdlib',
            'count_label': 'modules',
            'all': 'Tous',
            'overview': 'Aperçu',
            'view_category': 'Voir toute la catégorie',
            'view_all_list': 'Liste complète paginée',
            'page': 'Page',
            'showing': 'affichés',
            'prev': 'Précédent',
            'next': 'Suivant',
            'exports': 'Fonctions',
            'try_playground': 'Playground',
        },
        'libraries_page': {
            'title': 'Bibliothèques AFRILANG',
            'label': 'Stdlib',
            'h1': 'Toutes les bibliothèques',
            'lead': '7900+ modules stdlib avec descriptions, guides HTML et PDF explicatifs (5+ pages chacun).',
            'ultra_title': 'Paquets ultra (×500)',
            'ultra_lead': 'Familles générées : SIG, raster, segmentation, data science, visualisation, IA, bases de données, jeux.',
            'count_label': 'bibliothèques',
            'view_all': 'Voir tout',
            'guide': 'Guide',
            'guide_title': 'Guide',
            'guide_lead': 'Documentation imprimable — équivalent 5+ pages.',
            'print': 'Imprimer',
            'pages': 'pages',
            'api_title': 'Référence API',
            'fn_name': 'Fonction',
            'fn_params': 'Paramètres',
            'fn_returns': 'Retour',
            'pdf_note_title': 'Générer les PDF (LaTeX)',
            'pdf_note': 'Les PDF sont compilés en LaTeX (Tectonic ou XeLaTeX) via la commande de management.',
        },
        'releases_page': {
            'title': 'Versions AFRILANG',
            'label': 'Changelog',
            'h1': 'Historique des versions',
            'lead': 'Notes de version et nouveautés du compilateur et de la stdlib.',
            'empty': 'Aucune release — lancez python manage.py sync_releases',
        },
        'benchmarks_page': {
            'title': 'Benchmarks AFRILANG',
            'label': 'Performance',
            'h1': 'Benchmarks compilateur',
            'lead': 'Temps de compilation et d\'exécution sur les exemples officiels — transpilation C++17 puis binaire natif.',
            'sample_notice': 'Données indicatives — lancez sync_benchmarks pour des mesures réelles sur ce serveur.',
            'updated': 'Dernière mesure :',
            'stat_examples': 'Exemples',
            'stat_compile': 'Compile moy.',
            'stat_exec': 'Exec moy.',
            'stat_total': 'Total moy.',
            'chart_compile_exec': 'Compilation vs exécution',
            'chart_total': 'Temps total par exemple',
            'comparison_title': 'Comparaison exec (hello)',
            'comparison_lead': 'Même sortie console — binaire AFRILANG vs interpréteur Python 3.',
            'table_title': 'Résultats détaillés',
            'col_file': 'Fichier',
            'col_compile': 'Compile',
            'col_exec': 'Exec',
            'col_total': 'Total',
            'try_btn': 'Playground',
            'method_title': 'Méthodologie',
            'method_body': (
                'Mesures via <code>scripts/benchmark.sh</code> : '
                '<code>afrilang run fichier.afr --emit</code> (compile + link g++), '
                'puis exécution du binaire. Machine locale, une passe. '
                'Les temps varient selon CPU, cache et charge système.'
            ),
        },
        'showcase_page': {
            'title': 'Showcase AFRILANG',
            'label': 'Projets',
            'h1': 'Projets & dépôts',
            'lead': 'Compilateur, outils, site web, paquets et démos — l\'écosystème AFRILANG sur GitHub.',
            'featured': 'Projets phares',
            'try_btn': 'Playground',
            'submit_title': 'Votre projet en AFRILANG ?',
            'submit_lead': 'Publiez sur GitHub et ouvrez une issue pour apparaître dans cette galerie.',
            'submit_btn': 'Proposer un projet',
        },
        'errors_page': {
            'not_found_title': '404 — AFRILANG',
            'not_found_h1': 'Page introuvable',
            'not_found_lead': 'Cette URL n\'existe pas ou a été déplacée.',
            'not_found_code': '404 — page introuvable',
            'server_title': '500 — AFRILANG',
            'server_h1': 'Erreur serveur',
            'server_lead': 'Un problème est survenu de notre côté. Réessayez dans un instant.',
            'server_code': '500 — erreur serveur',
            'btn_home': 'Accueil',
            'btn_search': 'Rechercher dans la doc',
            'btn_retry': 'Réessayer',
            'btn_report': 'Signaler sur GitHub',
        },
        'docs_search_page': {
            'title': 'Recherche documentation',
            'h1': 'Rechercher dans la doc',
            'search': 'Mot-clé…',
            'filter': 'Rechercher',
            'hint': 'Entrez au moins 2 caractères pour lancer la recherche.',
            'min_chars': 'Entrez au moins 2 caractères.',
            'results_label': 'résultat(s)',
            'empty': 'Aucun résultat pour cette requête.',
        },
    },
    'en': {
        'nav_language': 'Language',
        'nav_docs': 'Documentation',
        'nav_ecosystem': 'Ecosystem',
        'nav_benchmarks': 'Benchmarks',
        'nav_showcase': 'Showcase',
        'nav_packages': 'Packages',
        'nav_playground': 'Playground',
        'nav_tutorial': 'Tutorial',
        'nav_examples': 'Examples',
        'nav_stdlib': 'Stdlib',
        'nav_libraries': 'Libraries',
        'nav_download': 'Download',
        'nav_community': 'Community',
        'nav_api': 'API',
        'nav_github': 'GitHub',
        'nav_start': 'Get started',
        'nav_theme_light': 'Light mode',
        'nav_theme_dark': 'Dark mode',
        'nav_version_label': 'Language · v',
        'skip_link': 'Skip to main content',
        'footer_learn': 'Learn',
        'footer_reference': 'Reference',
        'footer_community': 'Community',
        'footer_versions': 'Versions',
        'footer_lang': 'Language',
        'footer_compiler': 'Compiler',
        'footer_tagline': 'Code in sentences. Ship native binaries.',
        'footer_desc': (
            'Object-oriented language with natural-language syntax. Transpiles to C++17 '
            'and compiles to native binaries. Open source, MIT license.'
        ),
        'cookie_text': 'This site uses session cookies for language preference and the playground.',
        'cookie_accept': 'Accept',
        'cookie_decline': 'Decline',
        'meta_default': (
            'AFRILANG — natural-syntax OOP language transpiling to C++17, '
            'rich standard library, LSP tooling and web playground.'
        ),
        'home': {
            'title': 'AFRILANG — Code in sentences, ship native binaries',
            'badge': 'Open source · MIT',
            'hero_h1_a': 'Code in',
            'hero_h1_b': 'natural language',
            'hero_h1_c': 'compile to native.',
            'hero_lead': (
                'AFRILANG is a readable object-oriented language that transpiles to C++17. '
                'Classes, generics, pattern matching, async/await — with a standard library '
                'and a full developer toolchain.'
            ),
            'hero_compat': 'French & English syntax · LSP · REPL · WASM · cross-compilation',
            'btn_start': 'Get started',
            'btn_try': 'Try online',
            'btn_tutorial': 'Interactive tutorial',
            'stat_examples': 'Official examples',
            'stat_stdlib': 'Stdlib modules',
            'stat_packages': 'Certified packages',
            'stat_targets': 'Targets (x64, ARM, WASM)',
            'why_label': 'Why AFRILANG',
            'why_title': 'Readable like prose, fast like C++',
            'why_desc': (
                'Built for learning and production: natural syntax, clear errors, '
                'modern tooling and an African open-source ecosystem.'
            ),
            'feat_natural_title': 'Natural syntax',
            'feat_natural': (
                '<code>if age is greater than 18 then</code> instead of cryptic symbols. '
                'French keywords (<code>dire</code>, <code>si</code>, <code>fin</code>) or English.'
            ),
            'feat_perf_title': 'Native performance',
            'feat_perf': (
                'Transpilation to C++17 then <code>g++</code>. Native binaries, '
                'cross-compilation for linux-x64, linux-arm64 and wasm32.'
            ),
            'feat_modern_title': 'Modern & complete',
            'feat_modern': (
                'OOP, generics, enums, match, traits, async/await, Result, null-safety, '
                'operator overloading and FFI.'
            ),
            'feat_stdlib_title': 'Massive stdlib',
            'feat_stdlib': (
                'I/O, JSON, HTTP, GIS, raster, data science, AI, SQLite, 2D/3D games… '
                '7900+ modules via <code>import "std/…"</code>.'
            ),
            'feat_tools_title': 'Integrated toolchain',
            'feat_tools': (
                'CLI (<code>build</code>, <code>test</code>, <code>fmt</code>, <code>lint</code>), '
                'LSP 1.1, REPL, debug adapter, VS Code/Cursor extension, web playground.'
            ),
            'feat_africa_title': 'African open source',
            'feat_africa': (
                'Community MIT project. Package manager, official registry '
                'and full documentation to contribute.'
            ),
            'example_label': 'Quick example',
            'example_title': 'From sentence to binary in one command',
            'example_desc': (
                'Install the compiler, write a <code>.afr</code> file, run it. '
                'The pipeline transpiles to C++ and invokes <code>g++</code> automatically.'
            ),
            'packages_label': 'Ecosystem',
            'packages_title': 'Certified packages',
            'packages_all': 'View all →',
            'packages_empty': 'Empty registry — run <code>python manage.py sync_packages</code>',
            'cta_title': 'Ready to write your first program?',
            'cta_desc': 'Detailed docs, interactive playground and IDE extension — all included.',
            'cta_guide': 'Getting started guide',
            'cta_lang': 'Discover the language',
            'cta_play': 'Playground',
            'cta_tutorial': 'Interactive tutorial',
        },
        'tutorial_page': {
            'title': 'AFRILANG Tutorial',
            'label': 'Learn',
            'h1': 'Interactive tutorial',
            'lead': '7 guided lessons — from Hello World to OOP and pattern matching.',
            'sidebar': 'Path',
            'step_label': 'Step',
            'objectives': 'Objectives',
            'code_title': 'Lesson code',
            'copy': 'Copy',
            'try_playground': 'Try in playground',
            'challenge': 'Challenge',
            'prev': 'Previous',
            'next': 'Next',
            'overview': 'Overview',
            'mark_done': 'Mark as done',
            'finish': 'Install compiler',
            'read_doc': 'Read the docs →',
            'start': 'Start tutorial',
            'completed': 'completed',
        },
        'language_page': {
            'title': 'The AFRILANG language',
            'meta': 'AFRILANG overview: bilingual natural syntax, C++ transpilation, OOP, generics, async.',
            'label': 'AFRILANG {version}',
            'h1': 'A language you can read, a compiler that delivers',
            'lead': (
                'AFRILANG combines natural-language readability with a modern compiler. '
                'You write programs that read like sentences; the compiler transforms them '
                'into optimized C++17, then native executables.'
            ),
        },
        'download': {
            'title': 'Download AFRILANG',
            'h1': 'Install the compiler',
            'lead': 'Pre-built binary, install script or build from source.',
            'binary_title': 'Pre-built binary',
            'binary_lead': 'Download the compiler built on this server (Linux x64).',
            'binary_download': 'Download',
            'binary_none': 'No binary on this server — build from source or check GitHub Releases.',
            'binary_sha256': 'SHA256',
            'binary_size': 'Size',
            'install_title': 'Quick install',
            'install_lead': 'Bash script — clones, builds and installs to ~/.local/afrilang',
            'github_title': 'GitHub Releases',
            'github_lead': 'Official versions and CI artifacts on GitHub.',
            'github_btn': 'View releases',
            'requirements': 'Requirements',
            'build': 'Build from source',
            'verify': 'Verify',
            'ide': 'IDE extension',
        },
        'community': {
            'title': 'AFRILANG Community',
            'h1': 'Join the community',
            'lead': 'Contribute, report bugs, publish packages and participate in the open-source project.',
        },
        'api_page': {
            'title': 'REST API — Playground',
            'h1': 'Playground HTTP API',
            'lead': 'JSON endpoints to run, format and list AFRILANG packages.',
            'run_desc': 'Run AFRILANG source (native compilation).',
            'fmt_desc': 'Format source and return formatted code.',
            'pkg_desc': 'List all registry packages.',
        },
        'explore': {
            'title': 'AFRILANG Ecosystem',
            'label': 'Full ecosystem',
            'h1': 'Everything that makes AFRILANG',
            'lead': 'Language, compiler, stdlib, packages, WASM, LSP, debug and CI.',
            'empty': 'No data — run python manage.py seed_data',
            'btn_tools': 'Tooling docs',
            'btn_packages': 'Package registry',
        },
        'packages_page': {
            'title': 'AFRILANG Packages',
            'label': 'Package manager',
            'h1': 'Official registry',
            'lead': 'Certified packages (★) with SHA256 verification.',
            'search': 'Search packages…',
            'filter': 'Filter',
            'empty': 'No packages found.',
            'usage_title': 'Use a package',
        },
        'playground_page': {
            'title': 'AFRILANG Playground',
            'label': 'Try online',
            'h1': 'AFRILANG Playground',
            'lead': 'Write code, run, check or format it live.',
            'example': 'Example',
            'run': 'Run',
            'run_browser': 'Browser',
            'wasm': 'WASM in browser',
            'format': 'Format',
            'check': 'Check',
            'share': 'Share',
            'copy_output': 'Copy',
            'output': 'Output',
            'output_hint': 'Click Run to execute your code.',
            'help': 'See basic syntax or getting started.',
            'shortcut_run': 'Ctrl+Enter to run',
            'wasm_hint': 'Instant in-browser execution — no server load for simple programs.',
            'embed_link': 'Embed (iframe)',
        },
        'playground_embed_page': {
            'title': 'Embed playground',
            'label': 'Embed',
            'h1': 'Playground widget',
            'lead': 'Embed the AFRILANG editor in your blog, docs or site via an iframe.',
            'widget_title': 'AFRILANG Playground',
            'builder': 'Iframe builder',
            'example': 'Example',
            'height': 'Height (px)',
            'show_examples': 'Show example picker',
            'copy': 'Copy code',
            'code_title': 'HTML code',
            'preview': 'Preview',
            'open_widget': 'Open widget',
            'params_title': 'URL parameters',
            'param_example': 'preloaded example',
            'param_examples': 'example menu',
            'param_code': 'source code (URL-encoded)',
        },
        'examples_page': {
            'title': 'AFRILANG Examples',
            'label': 'Gallery',
            'h1': 'Official examples',
            'lead': 'Programs from the examples/ directory — open them in the playground in one click.',
            'search': 'Search examples…',
            'filter': 'Filter',
            'empty': 'No examples — run python manage.py sync_examples',
            'try_btn': 'Try it',
        },
        'stdlib_page': {
            'title': 'Standard library',
            'label': 'Stdlib',
            'h1': 'Stdlib browser',
            'lead': 'Browse all AFRILANG standard library modules.',
            'search': 'Search modules…',
            'filter': 'Filter',
            'empty': 'No modules — run python manage.py sync_stdlib',
            'count_label': 'modules',
            'all': 'All',
            'overview': 'Overview',
            'view_category': 'View full category',
            'view_all_list': 'Full paginated list',
            'page': 'Page',
            'showing': 'showing',
            'prev': 'Previous',
            'next': 'Next',
            'exports': 'Functions',
            'try_playground': 'Playground',
        },
        'libraries_page': {
            'title': 'AFRILANG Libraries',
            'label': 'Stdlib',
            'h1': 'All libraries',
            'lead': '7900+ stdlib modules with descriptions, HTML guides and explanatory PDFs (5+ pages each).',
            'ultra_title': 'Ultra packs (×500)',
            'ultra_lead': 'Generated families: GIS, raster, segmentation, data science, visualization, AI, databases, games.',
            'count_label': 'libraries',
            'view_all': 'View all',
            'guide': 'Guide',
            'guide_title': 'Guide',
            'guide_lead': 'Printable documentation — 5+ page equivalent.',
            'print': 'Print',
            'pages': 'pages',
            'api_title': 'API reference',
            'fn_name': 'Function',
            'fn_params': 'Parameters',
            'fn_returns': 'Returns',
            'pdf_note_title': 'Generate PDFs (LaTeX)',
            'pdf_note': 'PDFs are compiled from LaTeX (Tectonic or XeLaTeX) via the management command.',
        },
        'releases_page': {
            'title': 'AFRILANG Releases',
            'label': 'Changelog',
            'h1': 'Release history',
            'lead': 'Version notes and compiler/stdlib updates.',
            'empty': 'No releases — run python manage.py sync_releases',
        },
        'benchmarks_page': {
            'title': 'AFRILANG Benchmarks',
            'label': 'Performance',
            'h1': 'Compiler benchmarks',
            'lead': 'Compile and run times on official examples — C++17 transpilation then native binary.',
            'sample_notice': 'Sample data — run sync_benchmarks for real measurements on this server.',
            'updated': 'Last run:',
            'stat_examples': 'Examples',
            'stat_compile': 'Avg compile',
            'stat_exec': 'Avg exec',
            'stat_total': 'Avg total',
            'chart_compile_exec': 'Compile vs execution',
            'chart_total': 'Total time per example',
            'comparison_title': 'Exec comparison (hello)',
            'comparison_lead': 'Same console output — AFRILANG binary vs Python 3 interpreter.',
            'table_title': 'Detailed results',
            'col_file': 'File',
            'col_compile': 'Compile',
            'col_exec': 'Exec',
            'col_total': 'Total',
            'try_btn': 'Playground',
            'method_title': 'Methodology',
            'method_body': (
                'Measured via <code>scripts/benchmark.sh</code>: '
                '<code>afrilang run file.afr --emit</code> (compile + g++ link), '
                'then binary execution. Local machine, single pass. '
                'Times vary by CPU, cache and system load.'
            ),
        },
        'showcase_page': {
            'title': 'AFRILANG Showcase',
            'label': 'Projects',
            'h1': 'Projects & repositories',
            'lead': 'Compiler, tools, website, packages and demos — the AFRILANG ecosystem on GitHub.',
            'featured': 'Featured projects',
            'try_btn': 'Playground',
            'submit_title': 'Built something with AFRILANG?',
            'submit_lead': 'Publish on GitHub and open an issue to be listed in this gallery.',
            'submit_btn': 'Submit a project',
        },
        'errors_page': {
            'not_found_title': '404 — AFRILANG',
            'not_found_h1': 'Page not found',
            'not_found_lead': 'This URL does not exist or has been moved.',
            'not_found_code': '404 — page not found',
            'server_title': '500 — AFRILANG',
            'server_h1': 'Server error',
            'server_lead': 'Something went wrong on our side. Please try again shortly.',
            'server_code': '500 — server error',
            'btn_home': 'Home',
            'btn_search': 'Search docs',
            'btn_retry': 'Try again',
            'btn_report': 'Report on GitHub',
        },
        'docs_search_page': {
            'title': 'Documentation search',
            'h1': 'Search documentation',
            'search': 'Keyword…',
            'filter': 'Search',
            'hint': 'Enter at least 2 characters to search.',
            'min_chars': 'Enter at least 2 characters.',
            'results_label': 'result(s)',
            'empty': 'No results for this query.',
        },
    },
}


def get_ui(lang):
    code = (lang or 'fr')[:2]
    return UI.get(code, UI['fr'])
